# -*- coding: utf-8 -*-
"""twitter-scraping-query.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w9Cvr1W3l_rglmAhp5kwjgrIgoAZqD-1
"""

import os
import pandas as pd

print('Lutfen pip3 install snscrape komutunu kullanarak kullanarak kodun çalışması için gerekli kütüphaneyi kurunuz')

tweet_count = int(input('Kac adet tweet cekmek istiyorsunuz giriniz : '))
text_query = str(input('Lutfen arama yapmak istediginiz kelimeyi giriniz :'))
since_date = str(input('Hangi tarihler arasında arama yapmak istiyorsunuz , baslangıc tarihini YIL-AY-GUN (2022-06-01) Formatında giriniz : '))
until_date = str(input('Hangi tarihler arasında arama yapmak istiyorsunuz , bitis tarihini YIL-AY-GUN (2022-07-31) Formatında giriniz : '))


# Using OS library to call CLI commands in Python
os.system('snscrape --jsonl --max-results {} --since {} twitter-search "{} until:{}"> text-query-tweets.json'.format(tweet_count, since_date, text_query, until_date))
tweets_df2 = pd.read_json('text-query-tweets.json', lines=True)

tweets_df2.to_csv('text-query-tweets.csv', sep=',', index=False)

print('İslem basariyla tamamlanmistir')
